### ISSUE TITLE
Using C-[ in lieu of <escape>

### ISSUE THREAD

**Issue by bpstahlman** [noctuid/lispyville#21]
I've been wanting to switch to having "emacs" as my  "preferred" state, but for this to be practical, I need a quick and easy way to get from "emacs" state to "normal" state. The "escape theme" seemed to provide the solution; however, it seems to work only with the actual `<escape>` key, which I intentionally never use. (I've used `C-[` for years, to the point that it feels almost like a regular key to me at this point.)

So I've been poring over keymaps, keymap alists, etc..., trying to understand why `C-[` works in insert state, but not in emacs state. My hunch is that, when it works, it works because there's no meta prefix sub-map that would cause the ASCII 27 to be treated as a prefix key: e.g., nothing like this in the active maps...
```
(27 keymap
		    (108 . lispyville-end-of-defun)
		    (104 . lispyville-beginning-of-defun))

```
Is this the case? What's confusing me though is that in both cases (insert and emacs states) I can see such submaps in the output of `(current-active-maps)`, and yet, there's definitely something different going on in the insert state case. In emacs state, `C-[` is being treated as `<escape>`, which is mapped to `lispyville-escape`, but in insert state, it's treated as ESC-prefix: i.e., I'm prompted with `ESC-` in the minibuffer, and emacs simply waits for the next key.

Is the problem that emacs state has meta mappings and evil insert state doesn't? And if that's the case, am I correct in assuming what I'm trying to do can't be done? If you have any advice on how to search through active keymaps to see exactly which bindings emacs would find in a give minor mode, I'd greatly appreciate it. I must be missing something, because I'm seeing what look like active meta key submaps even in the evil insert state case, and yet `C-[` gets mapped to `<escape>` somehow in insert state.

**Comment by noctuid** [comment]
If I recall correctly, evil may handle escape specially. You'd probably be better off asking on the evil irc or in the [new repo](https://github.com/emacs-evil/evil/). It may have to do with escape being used for meta, but `C-[` still works for me in insert state with meta keymappings existing. I don't use emacs state or `C-[`, so I've never run into this issue before.

**Comment by bpstahlman** [comment]
Ok. Thanks. The reason I was considering making "emacs" state preferred is that I wanted access to stuff like `M-k`, `C-k` and `M-w`, but now I'm thinking maybe I could just use lispyville's operators and movements after escaping back to normal or visual state: e.g., instead of hitting `M-k` in emacs state to delete to end of current list, I could escape back to normal state and do `d )`. I haven't used the lispyville motions much yet, but I'm thinking I need to familiarize myself with them before making a decision. Is this pretty much the approach you use?

**Comment by noctuid** [comment]
You could also bind/unbind the keys you want in insert state if emacs state causes problems. For the most common deletion operations like for lines/sexps, it's probably worth using a modifier (ideally one on a thumb key like alt) instead of entering normal state. I don't use lispyville's motions much myself.

**Comment by bpstahlman** [comment]
Ok. So I've dug around a bit in the evil source. The magic you alluded to is in `input-decode-map` and its associated "filter" function `evil-esc`. The primary purpose of this filtering is to do ASCII control char translations, but the translation is skipped when you're in evil emacs state. So the bottom line is, I probably need to avoid reliance on `C-[` if I'm going to be making significant use of emacs state. This leaves me with either the `<escape>` key (a non-starter for me due to its location on the keyboard) or perhaps an unordered key-chord such as `jk` with a very short delay (e.g., 0.01 seconds). I've played with the key-chord approach a bit. It's not bad, but even with the shortest delay it can handle, there's a slight but noticeable flicker when moving up and down by sexp with `j` and `k`. I suppose I could live with it, but it's not ideal.

But perhaps the better solution is just to avoid emacs state altogether. As you point out, I can map whatever commands I need in insert state, possibly unmapping (or moving to less convenient key sequences) commands like `evil-insert-digraph` (`C-k`), whose functionality is needed very infrequently compared to that of a command like `kill-line`.

Incidentally, as I was playing around with this, I noticed that mark toggle seemed to work properly only when I set preferred state to insert. When preferred state is emacs...

1. First call to `lispyville-toggle-mark-type` marks symbol and changes to emacs state
2. Second call to `lispyville-toggle-mark-type` leaves symbol marked and changes to visual state
3. Third call to `lispyville-toggle-mark-type` *unmarks* symbol, changes back to emacs state, and leaves point past the previously marked symbol.

I was thinking something like this had been fixed at some point, but perhaps I'm misremembering. I appear to have the latest release.

**Comment by noctuid** [comment]
I personally think that escape is used enough to warrant a dedicated key. A lot of people dual-role capslock as escape and control. I like having it on a thumbkey like left alt.

I used the key-chord approach for a while, but it ended up being unusable for me whenever I had any input lag (even typing the chord slowly will trigger it with lag). I don't remember any bad flickering; I tried it out now and didn't notice any (with a delay of 0.02).

The previous problem happened when transitioning to visual state. It seems the region gets cancelled when transitioning from visual to emacs state as well. It should be fixed now. Sorry about that, and thanks for reporting.

**Comment by bpstahlman** [comment]
I agree about escape warranting its own key; I guess `C-[` is so quick and easy for me that it feels like its own key. I find it more convenient than either of the Alt keys, though that may be because I've generally treated the Alt keys as middle finger keys, not thumb keys. Perhaps if I'd learned them as thumb keys initially I'd feel differently about it. Another one of those early training things that prevents my dual-purposing a key for Control is that I've always insisted on pressing the key modified by Control with the opposite hand. I could be wrong, but I suspect that using only Left-Alt, even with the thumb, could lead to some awkward combinations for a touch-typist (e.g., `M-t`, `M-z`).

Though I do often run in a terminal, I wouldn't think lag should be an issue if I pick the key-chord combinations intelligently: e.g., I would type `jk` and `fj` so infrequently, that the inconvenience of having to use `C-q` to insert one of the keys in the pair (or even waiting a second or two to type the second), would be more than offset by the convenience of having escape so easily accessible. In fact, I'm experimenting with dual-purposing `jk` as escape (in non-normal state) and a Control key of sorts (by tying it to `evil-god-state` in normal state). I guess now that I've seen the possibilities, I've gotten greedy for more ways to minimize the use of Control and Meta keys. I actually considered some sort of foot pedal rig, but I often work at a standing desk, so I'm not sure how feasible that would be. Perhaps there's a keyboard that would change my feelings on this point: e.g., one whose space bar is shorter, allowing a meta key placement that does not require my thumbs to move so far outwards.

Ultimately, I think it comes down to my search for efficiency and elegance: key-chords are an efficient and elegant way to re-purpose otherwise wasted keyboard real estate. Evil's use of modes is similarly elegant and efficient, as is Spacemacs' use of the spacebar, a key which is eminently accessible, but almost never used in normal mode. Control/Meta keys *_can_* be elegant and efficient, but only if they're sufficiently accessible. And for me, certain Control/Meta keys are significantly less accessible than others: e.g., `C-[` is very accessible, but `C-z` and `C-x`, for instance, are not. And then there's Colemak... Perhaps my quest for efficiency will lead me there, though I suspect it would improve efficiency only with self-insert typing, which isn't really my primary concern at this point. On the other hand, if I'm going to learn a new system, I'd probably want to learn it once, on the keyboard layout I plan to use ultimately...

**Comment by noctuid** [comment]
I generally have my left thumb resting pretty close to lalt, so for me it's a very convenient position. I also use super/the win key as a thumbkey. I have pretty sensitive pinkies, so I pretty much never use control. The more common key to use for escape is capslock though.

In my case it's a lot more likely to happen since I use colemak-dh (`ne`, for example, is a lot more common), but if I remember correctly, typing something like `joke` will also trigger the chord with lag.

My current emacs config doesn't use control or alt much at all apart from a couple default keys (`C-q`, `M-q`, and `C-h` mainly). I've been trying to use more modifiers via thumbkeys and potentially dual-roling home row keys and space. Modality is great in a lot of situtions, but it's not optimal for one-off actions. I've always used modifiers for basic line navigation, global hotkeys, and window management. I'd never use modifiers for everything like emacs does by default, but they are good for certain situations (the same is true for key-chord). They often get a bad rap because of the poor design of the keyboard though, which makes them less usable like you point out.

I looked into buying keyboards for years without finding one I really liked before the keyboardio model 01. It address the problems I have with normal keyboards better than other ergonomic keyboards (ergonomics: adjustable tenting, vertical not horizontal stagger, optionally splittable, etc.; efficiency: 8 thumbkeys and 2 palm keys that are more reachable than on some other ergonomic keyboards, hardware remappable/highly-customizable with keyboard firmware). I purchased one during the kickstarter, but it's not out yet, and it's **very** expensive. An inexpensive Japanese keyboard is an alternative if you just want a couple more thumbkeys. I used one for a while. Another problem I have with keyboards is that I use a laptop, and it's not really practical for me to carry around a keyboard with me everywhere. Dual-role and using the few available thumbkeys are the strategies I use currently to make modifiers more viable on a standard keyboard. I use a wide keyboard layout (right-hand shifted over a key) which also makes using right alt as a thumbkey easier.

As for keyboard layouts, they don't really matter when it comes to speed. Large speed gains after switching layouts are more likely a result of practice/retraining or learning to touch type for the first time.

**Comment by bpstahlman** [comment]
Wow! Keyboardio looks really nice. From the looks of it, its Control/Meta key placement could almost make the default emacs keybindings bearable...

**Comment by sooheon** [comment]
@bpstahlman FYI, there is also the evil variable `evil-disable-insert-state-bindings` to look at if you want it to be more like emacs state

**Comment by noctuid** [comment]
Since I can't really do anything about this in lispyville, I'm going to go ahead and close the issue.
