### ISSUE TITLE
Does not rebind anything

### ISSUE THREAD

**Issue by Vurp** [noctuid/lispyville#46]
lispyville does not seem to rebind any keys after I enable it with
`M-x lispyville-mode`. If I call lispyville commands directly with
`M-x` such as `M-x lispyville-delete` they work fine.

These are the versions of related packages that I have installed:

Package | Version
---- | -----
evil | 1.2.13
lispy | 20181004.1959
lispyville | 20180704.1158

This is my config:

    (use-package lispyville
      :after lispy
      :init
    (setq lispyville-key-theme
            '(operators
            c-w
            prettify)))

    ;; Required for lispyville
    (use-package lispy
      :pin melpa)

**Comment by noctuid** [comment]
Right now you have lispyville to only load after lispy is loaded. Do you ever load lispy?

**Comment by noctuid** [comment]
Evil 1.2.13 is about a year old, and lispyville requires a newer version of evil (to make keybindings for example). If you are using the melpa stable package, you'll need to update.

**Comment by Vurp** [comment]
> Evil 1.2.13 is about a year old, and lispyville requires a newer version of evil (to make keybindings for example). If you are using the melpa stable package, you'll need to update.

That was the issue. I try to stick to melpa-stable as I imagine packages will be more stable if I do.

**Comment by noctuid** [comment]
Evil has had a ton of improvements since the last release. Generally, I think it's better to just stick with melpa. If you're worried about breakage, it's probably better to have some way to revert to older versions of packages (e.g. some people incrementally backup all their packages; there are also package managers like straight.el that allow easily locking package revisions).
